// Generate games/lexicon/words.js from the system dictionary already on this machine.
// Zero downloads: /usr/share/dict/words ships with macOS and most Unixes.
//
//   node tools/gen-words.mjs
//
// Output is a single newline-joined string split at runtime into a Set — far smaller
// and faster to parse than a JSON array of 70k strings.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SOURCES = ['/usr/share/dict/words', '/usr/dict/words', '/usr/share/dict/web2'];

const src = SOURCES.find((p) => existsSync(p));
if (!src) {
  console.error('No system dictionary found. Looked in:\n  ' + SOURCES.join('\n  '));
  process.exit(1);
}

const MIN = 3, MAX = 8;
const raw = readFileSync(src, 'utf8').split('\n');
const words = [];
const seen = new Set();

for (const line of raw) {
  const w = line.trim();
  if (w.length < MIN || w.length > MAX) continue;
  if (!/^[a-z]+$/.test(w)) continue;       // lowercase only — drops proper nouns
  if (seen.has(w)) continue;
  seen.add(w);
  words.push(w);
}

words.sort();

const byLen = {};
for (const w of words) byLen[w.length] = (byLen[w.length] || 0) + 1;

const out = `// Generated by tools/gen-words.mjs from ${src} — do not edit by hand.
// ${words.length} words, ${MIN}-${MAX} letters, lowercase only.
// Stored as one newline-joined string: ~4x smaller and ~10x faster to parse than a JSON array.

const RAW = ${JSON.stringify(words.join('\n'))};

let _set = null;
/** Lazily built Set of every valid word. */
export function words() {
  if (!_set) _set = new Set(RAW.split('\\n'));
  return _set;
}
export function isWord(w) {
  return words().has(String(w).toLowerCase());
}
export const WORD_COUNT = ${words.length};
export const MIN_LEN = ${MIN};
export const MAX_LEN = ${MAX};
export default words;
`;

const dest = join(ROOT, 'games', 'lexicon', 'words.js');
writeFileSync(dest, out);

const kb = (Buffer.byteLength(out) / 1024).toFixed(0);
console.log(`wrote ${dest}`);
console.log(`  source : ${src}`);
console.log(`  words  : ${words.length}`);
console.log(`  size   : ${kb} KB raw (GitHub Pages serves it gzipped)`);
console.log(`  by len : ${Object.entries(byLen).map(([k, v]) => `${k}:${v}`).join('  ')}`);
